# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "ko-KR"

reviews:
  profile: "assertive"
  review_status: true
  request_changes_workflow: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: true
    base_branches:
      - ".*"
