spring:
  application:
    name: sb13-monew-team04
  profiles:
    default: dev
  jpa:
    open-in-view: false

springdoc:
  api-docs:
    # OpenAPI 명세 제공 경로
    path: /v3/api-docs

  swagger-ui:
    # Swagger UI 설정
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

monew:
  news:
    naver:
      base-url: https://openapi.naver.com
      path: /v1/search/news.json
      client-id: ${MONEW_NAVER_CLIENT_ID:}
      client-secret: ${MONEW_NAVER_CLIENT_SECRET:}
      connect-timeout: ${MONEW_NAVER_CONNECT_TIMEOUT:3s}
      read-timeout: ${MONEW_NAVER_READ_TIMEOUT:5s}
  openapi:
    server-url: http://localhost:${server.port:8080}
    server-description: 로컬 개발 서버
