spring:
  application:
    name: sb13-monew-team04
  profiles:
    default: dev
  jpa:
    open-in-view: false

springdoc:
  api-docs:
    # OpenAPI 명세 제공 경로
    path: /v3/api-docs

  swagger-ui:
    # Swagger UI 설정
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

monew:
  openapi:
    server-url: http://localhost:${server.port:8080}
    server-description: 로컬 개발 서버
