spring:
  application:
    name: sb13-monew-team04
  profiles:
    default: dev
  jpa:
    open-in-view: false

springdoc:
  api-docs:
    # OpenAPI 명세 제공 경로
    path: /v3/api-docs

  swagger-ui:
    # Swagger UI 설정
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

monew:
  news:
    naver:
      base-url: https://openapi.naver.com
      path: /v1/search/news.json
      client-id: ${MONEW_NAVER_CLIENT_ID:}
      client-secret: ${MONEW_NAVER_CLIENT_SECRET:}
      connect-timeout: ${MONEW_NAVER_CONNECT_TIMEOUT:3s}
      read-timeout: ${MONEW_NAVER_READ_TIMEOUT:5s}
    rss:
      connect-timeout: ${MONEW_RSS_CONNECT_TIMEOUT:3s}
      read-timeout: ${MONEW_RSS_READ_TIMEOUT:5s}
      hankyung:
        base-url: https://www.hankyung.com/feed
      chosun:
        base-url: https://www.chosun.com/arc/outboundfeeds/rss
      yonhap:
        base-url: https://www.yonhapnewstv.co.kr
  s3:
    bucket: ${MONEW_ARTICLE_BACKUP_S3_BUCKET}
    region: ${MONEW_AWS_REGION}
    endpoint: ${MONEW_AWS_ENDPOINT}
    prefix: ${MONEW_ARTICLE_BACKUP_S3_PREFIX}
  backup:
    schedule:
      enabled: ${MONEW_ARTICLE_BACKUP_ENABLED:false}
      cron: "${MONEW_ARTICLE_BACKUP_CRON:0 10 0 * * *}"
  collect:
    schedule:
      enabled: ${MONEW_ARTICLE_COLLECT_ENABLED:false}
      cron: "${MONEW_ARTICLE_COLLECT_CRON:0 0/10 * * * *}"

  openapi:
    server-url: http://localhost:${server.port:8080}
    server-description: 로컬 개발 서버
